### ISSUE TITLE
var pixelWidth

### ISSUE THREAD

**Issue by mdoussias** [team-makeSmart/CST325#7]
In the file **raytracer-skeleton.html**

I'm a little unclear on what needs done.
I think to set the pixelWidth variable we need the following code because the width is not set by the amount of pixels, but rather by the amount of space the pixel takes up in the virtual world.   
      
**var pixelWidth = (pixelsAcross * pixelScale); **

This might be wrong though... Still reading.

**Comment by Mcghee-Jake** [comment]
I'm working on this now as well. I asked the professor about it because I was confused by what the pixelWidth was suppose to represent. Here was his response:

"The pixelScale is only there to increase the size of your image for better viewing.  So basically every 1 pixel turns into a 3x3 pixel block.  For this assignment you can basically ignore it. As for size that a pixel takes in the world, we've decided ahead of time that the pixel grid would exist in our world with the top left at (-1, 1, 0) and top right at (1, 1, 0).  So that defines the space it occupies in the world.  Now, given the resolution, you must divide the space evenly for the number of pixels that are supposed to occupy it."
